apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "https://github.com/hballow2008/open-flights-project"
        - name: revision
          value: "main"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "docker.io/hballow/open-flights-project-web:latest"
    - name: push-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "docker.io/hballow/open-flights-project-web:latest"
        - name: TLSVERIFY
          value: "false"
