apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/hballow2008/open-flights-project"
    - name: build-and-push
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: "docker.io/hballow/open-flights-project-web"
